/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visuales;
import static visuales.JuegoJava.activos;
import static visuales.JuegoJava.espa;

/**
 *
 * @author Karla
 */
public class pantallaTablero extends javax.swing.JFrame {
    /**
     *
     */
    
   // public int espa, mate, hist, geo, cult;
    int puntaje;
    
    public void juego(){
        
        /**
         * Método para cambiar de pantalla al interactuar con la actual.
         * se crea un objeto "volver" relacionado a la pantalla a la que se quiere devolver
         * crea entonces una nueva pantalla que tenga el nombre de la seleccionada (en este caso, la de pantallaJuego)
         * hace visible la pantalla
         * y cierra la que estaba antes (la actual).
         */
        pantallaJuego ObjVolver;
        ObjVolver = new pantallaJuego();
        ObjVolver.setVisible(true);
        this.setVisible(false);
        esp50.setEnabled(JuegoJava.activos[0][0]);
        esp100.setEnabled(JuegoJava.activos[1][0]);
        esp150.setEnabled(JuegoJava.activos[2][0]);
        esp200.setEnabled(JuegoJava.activos[3][0]);
        esp300.setEnabled(JuegoJava.activos[4][0]);
        esp500.setEnabled(JuegoJava.activos[5][0]);
        /*mate50.setEnabled(JuegoJava.activos[0][1]);
        mate100.setEnabled(JuegoJava.activos[1][1]);
        mate150.setEnabled(JuegoJava.activos[2][1]);
        mate200.setEnabled(JuegoJava.activos[3][1]);
        mate300.setEnabled(JuegoJava.activos[4][1]);
        mate500.setEnabled(JuegoJava.activos[5][1]);*/
        
    }
    /**
     * Creates new form pantallaTablero
     */
    public pantallaTablero() {
        initComponents();
        
        
        esp50.setEnabled(JuegoJava.activos[0][0]);
        esp100.setEnabled(JuegoJava.activos[1][0]);
        esp150.setEnabled(JuegoJava.activos[2][0]);
        esp200.setEnabled(JuegoJava.activos[3][0]);
        esp300.setEnabled(JuegoJava.activos[4][0]);
        esp500.setEnabled(JuegoJava.activos[5][0]);
        /*mate50.setEnabled(JuegoJava.activos[0][1]);
        mate100.setEnabled(JuegoJava.activos[1][1]);
        mate150.setEnabled(JuegoJava.activos[2][1]);
        mate200.setEnabled(JuegoJava.activos[3][1]);
        mate300.setEnabled(JuegoJava.activos[4][1]);
        mate500.setEnabled(JuegoJava.activos[5][1]);*/
        /*if((activos[0][0]=false) && (activos[1][0]=false) && (activos[2][0]=false) && (activos[3][0]=false) && (activos[4][0]=false) && (activos[5][0]=false)){
            activos[0][0]=true;
            activos[1][0]=true;
            activos[2][0]=true;
            activos[3][0]=true;
            activos[4][0]=true;
            activos[5][0]=true;
            JuegoJava.puntaje=0;
        }*/
        this.setLocationRelativeTo(this); //hace que la posición de la pantalla sea relativa a la resolución del equipo. 
        // pone la pantalla en medio.
        
        lbPuntaje.setText(String.valueOf(JuegoJava.puntaje));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton37 = new javax.swing.JButton();
        esp50 = new javax.swing.JButton();
        esp100 = new javax.swing.JButton();
        esp150 = new javax.swing.JButton();
        esp200 = new javax.swing.JButton();
        esp300 = new javax.swing.JButton();
        esp500 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        mate50 = new javax.swing.JButton();
        mate100 = new javax.swing.JButton();
        mate150 = new javax.swing.JButton();
        mate200 = new javax.swing.JButton();
        mate300 = new javax.swing.JButton();
        mate500 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        hist50 = new javax.swing.JButton();
        hist100 = new javax.swing.JButton();
        hist150 = new javax.swing.JButton();
        hist200 = new javax.swing.JButton();
        hist300 = new javax.swing.JButton();
        hist500 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        geo50 = new javax.swing.JButton();
        geo100 = new javax.swing.JButton();
        geo150 = new javax.swing.JButton();
        geo200 = new javax.swing.JButton();
        geo300 = new javax.swing.JButton();
        geo500 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        cult50 = new javax.swing.JButton();
        cult100 = new javax.swing.JButton();
        cult150 = new javax.swing.JButton();
        cult200 = new javax.swing.JButton();
        cult300 = new javax.swing.JButton();
        cult500 = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbPuntaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 700));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));

        jPanel1.setBackground(new java.awt.Color(154, 237, 255));

        jPanel2.setBackground(new java.awt.Color(212, 238, 113));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/espanol.png"))); // NOI18N
        jButton37.setContentAreaFilled(false);

        esp50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/50.png"))); // NOI18N
        esp50.setContentAreaFilled(false);
        esp50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esp50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp50ActionPerformed(evt);
            }
        });

        esp100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/100.png"))); // NOI18N
        esp100.setContentAreaFilled(false);
        esp100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esp100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp100ActionPerformed(evt);
            }
        });

        esp150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/150.png"))); // NOI18N
        esp150.setContentAreaFilled(false);
        esp150.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esp150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp150ActionPerformed(evt);
            }
        });

        esp200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/200.png"))); // NOI18N
        esp200.setContentAreaFilled(false);
        esp200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esp200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp200ActionPerformed(evt);
            }
        });

        esp300.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/300.png"))); // NOI18N
        esp300.setContentAreaFilled(false);
        esp300.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esp300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp300ActionPerformed(evt);
            }
        });

        esp500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/500.png"))); // NOI18N
        esp500.setContentAreaFilled(false);
        esp500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esp500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp500ActionPerformed(evt);
            }
        });

        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/matematicas.png"))); // NOI18N
        jButton43.setContentAreaFilled(false);
        jButton43.setEnabled(false);

        mate50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/50.png"))); // NOI18N
        mate50.setContentAreaFilled(false);
        mate50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mate50.setEnabled(false);
        mate50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mate50ActionPerformed(evt);
            }
        });

        mate100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/100.png"))); // NOI18N
        mate100.setContentAreaFilled(false);
        mate100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mate100.setEnabled(false);
        mate100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mate100ActionPerformed(evt);
            }
        });

        mate150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/150.png"))); // NOI18N
        mate150.setContentAreaFilled(false);
        mate150.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mate150.setEnabled(false);
        mate150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mate150ActionPerformed(evt);
            }
        });

        mate200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/200.png"))); // NOI18N
        mate200.setContentAreaFilled(false);
        mate200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mate200.setEnabled(false);
        mate200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mate200ActionPerformed(evt);
            }
        });

        mate300.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/300.png"))); // NOI18N
        mate300.setContentAreaFilled(false);
        mate300.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mate300.setEnabled(false);
        mate300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mate300ActionPerformed(evt);
            }
        });

        mate500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/500.png"))); // NOI18N
        mate500.setContentAreaFilled(false);
        mate500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mate500.setEnabled(false);
        mate500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mate500ActionPerformed(evt);
            }
        });

        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/historia.png"))); // NOI18N
        jButton47.setContentAreaFilled(false);
        jButton47.setEnabled(false);

        hist50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/50.png"))); // NOI18N
        hist50.setContentAreaFilled(false);
        hist50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hist50.setEnabled(false);
        hist50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hist50ActionPerformed(evt);
            }
        });

        hist100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/100.png"))); // NOI18N
        hist100.setContentAreaFilled(false);
        hist100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hist100.setEnabled(false);
        hist100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hist100ActionPerformed(evt);
            }
        });

        hist150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/150.png"))); // NOI18N
        hist150.setContentAreaFilled(false);
        hist150.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hist150.setEnabled(false);
        hist150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hist150ActionPerformed(evt);
            }
        });

        hist200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/200.png"))); // NOI18N
        hist200.setContentAreaFilled(false);
        hist200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hist200.setEnabled(false);
        hist200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hist200ActionPerformed(evt);
            }
        });

        hist300.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/300.png"))); // NOI18N
        hist300.setContentAreaFilled(false);
        hist300.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hist300.setEnabled(false);
        hist300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hist300ActionPerformed(evt);
            }
        });

        hist500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/500.png"))); // NOI18N
        hist500.setContentAreaFilled(false);
        hist500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hist500.setEnabled(false);
        hist500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hist500ActionPerformed(evt);
            }
        });

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/geografia.png"))); // NOI18N
        jButton50.setContentAreaFilled(false);
        jButton50.setEnabled(false);

        geo50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/50.png"))); // NOI18N
        geo50.setContentAreaFilled(false);
        geo50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geo50.setEnabled(false);
        geo50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geo50ActionPerformed(evt);
            }
        });

        geo100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/100.png"))); // NOI18N
        geo100.setContentAreaFilled(false);
        geo100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geo100.setEnabled(false);
        geo100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geo100ActionPerformed(evt);
            }
        });

        geo150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/150.png"))); // NOI18N
        geo150.setContentAreaFilled(false);
        geo150.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geo150.setEnabled(false);
        geo150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geo150ActionPerformed(evt);
            }
        });

        geo200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/200.png"))); // NOI18N
        geo200.setContentAreaFilled(false);
        geo200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geo200.setEnabled(false);
        geo200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geo200ActionPerformed(evt);
            }
        });

        geo300.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/300.png"))); // NOI18N
        geo300.setContentAreaFilled(false);
        geo300.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geo300.setEnabled(false);
        geo300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geo300ActionPerformed(evt);
            }
        });

        geo500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/500.png"))); // NOI18N
        geo500.setContentAreaFilled(false);
        geo500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geo500.setEnabled(false);
        geo500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geo500ActionPerformed(evt);
            }
        });

        jButton56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/cultura.png"))); // NOI18N
        jButton56.setContentAreaFilled(false);
        jButton56.setEnabled(false);

        cult50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/50.png"))); // NOI18N
        cult50.setContentAreaFilled(false);
        cult50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cult50.setEnabled(false);
        cult50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cult50ActionPerformed(evt);
            }
        });

        cult100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/100.png"))); // NOI18N
        cult100.setContentAreaFilled(false);
        cult100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cult100.setEnabled(false);
        cult100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cult100ActionPerformed(evt);
            }
        });

        cult150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/150.png"))); // NOI18N
        cult150.setContentAreaFilled(false);
        cult150.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cult150.setEnabled(false);
        cult150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cult150ActionPerformed(evt);
            }
        });

        cult200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/200.png"))); // NOI18N
        cult200.setContentAreaFilled(false);
        cult200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cult200.setEnabled(false);
        cult200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cult200ActionPerformed(evt);
            }
        });

        cult300.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/300.png"))); // NOI18N
        cult300.setContentAreaFilled(false);
        cult300.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cult300.setEnabled(false);
        cult300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cult300ActionPerformed(evt);
            }
        });

        cult500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/500.png"))); // NOI18N
        cult500.setContentAreaFilled(false);
        cult500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cult500.setEnabled(false);
        cult500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cult500ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esp500, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp300, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp200, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp150, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp100, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp50, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mate500, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mate300, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mate200, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mate150, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mate100, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mate50, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hist500, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist300, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist200, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist150, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist100, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist50, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geo500, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo300, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo200, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo150, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo100, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo50, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cult300, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(cult200, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cult150, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cult100, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cult50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cult500, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton47, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton43, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mate50, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp50, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist50, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo50, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cult50, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geo100, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cult100, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist100, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mate100, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp100, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mate150, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp150, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist150, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo150, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cult150, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mate200, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp200, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist200, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo200, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cult200, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esp300, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mate300, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist300, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo300, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cult300, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cult500, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geo500, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hist500, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mate500, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp500, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/arrow40px.png"))); // NOI18N
        botonVolver.setContentAreaFilled(false);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/cerrar30px.png"))); // NOI18N
        botonSalir.setContentAreaFilled(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 82)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visuales/mixUp.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        jPanel3.setBackground(new java.awt.Color(255, 244, 90));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Puntuación:");

        lbPuntaje.setEditable(false);
        lbPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbPuntajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addComponent(lbPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        pantallaSeleccion ObjVolver = new pantallaSeleccion(); 
        ObjVolver.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        pantallaInicio ObjVolver = new pantallaInicio();
        ObjVolver.setVisible(true);
        dispose();
        /**
         * CÓDIGO PARA DEVOLVER LOS VALORES DE LOS BOTONES A ENABLED = TRUE AL INICIAR UNA NUEVA PARTIDA.
         */
        
        
        /*if((activos[0][0]=false) && (activos[1][0]=false) && (activos[2][0]=false) && (activos[3][0]=false) && (activos[4][0]=false) && (activos[5][0]=false)){
            activos[0][0]=true;
            activos[1][0]=true;
            activos[2][0]=true;
            activos[3][0]=true;
            activos[4][0]=true;
            activos[5][0]=true;
            JuegoJava.puntaje=0;
        }*/
    }//GEN-LAST:event_botonSalirActionPerformed

    private void esp50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp50ActionPerformed
        JuegoJava.setEspa(1);//ESPAÑOL 1
        JuegoJava.activos[0][0]=!JuegoJava.activos[0][0];
        esp50.setEnabled(JuegoJava.activos[0][0]);
        //JuegoJava.setEspa(1); //corregido por: Ramón Lopez Vargas (cambiando de lugar el seter y el metodo)
        //esp50.setEnabled(false); 
        this.setVisible(false);
        juego();
         //cambio
        
    }//GEN-LAST:event_esp50ActionPerformed

    private void mate50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mate50ActionPerformed
        JuegoJava.setMate(7); //MATEMATICAS 1
        //mate50.setEnabled(false);
        JuegoJava.activos[0][1]=!JuegoJava.activos[0][1];
        mate50.setEnabled(JuegoJava.activos[0][1]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_mate50ActionPerformed

    private void hist50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hist50ActionPerformed
        JuegoJava.setHist(13);//HISTORIA 1
        juego();
        
    }//GEN-LAST:event_hist50ActionPerformed

    private void cult50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cult50ActionPerformed
        JuegoJava.setCult(25);//CULTURA 1
        juego();
        
    }//GEN-LAST:event_cult50ActionPerformed

    private void esp100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp100ActionPerformed
        JuegoJava.setEspa(2);//ESPAÑOL 2
        JuegoJava.activos[1][0]=!JuegoJava.activos[1][0];
        esp100.setEnabled(JuegoJava.activos[1][0]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_esp100ActionPerformed

    private void mate100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mate100ActionPerformed
        JuegoJava.setMate(8);//MATEMATICAS 2
        JuegoJava.activos[1][1]=!JuegoJava.activos[1][1];
        mate100.setEnabled(JuegoJava.activos[1][1]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_mate100ActionPerformed

    private void hist100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hist100ActionPerformed
        JuegoJava.setHist(14);//HISTORIA 2
        juego();
        
    }//GEN-LAST:event_hist100ActionPerformed

    private void geo100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geo100ActionPerformed
        JuegoJava.setGeo(20);//GEOGRAFIA 2
        juego();
        
        
    }//GEN-LAST:event_geo100ActionPerformed

    private void cult100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cult100ActionPerformed
        JuegoJava.setCult(25);//CULTURA 2
        juego();
        
    }//GEN-LAST:event_cult100ActionPerformed

    private void esp150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp150ActionPerformed
        JuegoJava.setEspa(3);//ESPAÑOL 3
        JuegoJava.activos[2][0]=!JuegoJava.activos[2][0];
        esp150.setEnabled(JuegoJava.activos[2][0]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_esp150ActionPerformed

    private void mate150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mate150ActionPerformed
        JuegoJava.setMate(9);//MATEMATICAS 3
        JuegoJava.activos[2][1]=!JuegoJava.activos[2][1];
        mate150.setEnabled(JuegoJava.activos[2][1]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_mate150ActionPerformed

    private void hist150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hist150ActionPerformed
        JuegoJava.setHist(15);//HISTORIA 3
        juego();
        
    }//GEN-LAST:event_hist150ActionPerformed

    private void geo150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geo150ActionPerformed
        JuegoJava.setGeo(21);//GEOGRAFIA 3
        juego();
        
    }//GEN-LAST:event_geo150ActionPerformed

    private void cult150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cult150ActionPerformed
        JuegoJava.setCult(27);//CULTURA 3
        juego();
        
    }//GEN-LAST:event_cult150ActionPerformed

    private void esp200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp200ActionPerformed
        JuegoJava.setEspa(4);
        JuegoJava.activos[3][0]=!JuegoJava.activos[3][0];
        esp200.setEnabled(JuegoJava.activos[3][0]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_esp200ActionPerformed

    private void mate200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mate200ActionPerformed
        JuegoJava.setMate(10);
        JuegoJava.activos[3][1]=!JuegoJava.activos[3][1];
        mate200.setEnabled(JuegoJava.activos[3][1]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_mate200ActionPerformed

    private void hist200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hist200ActionPerformed
        JuegoJava.setHist(16);
        juego();
        
    }//GEN-LAST:event_hist200ActionPerformed

    private void geo200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geo200ActionPerformed
        JuegoJava.setGeo(22);
        juego();
        
    }//GEN-LAST:event_geo200ActionPerformed

    private void cult200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cult200ActionPerformed
        JuegoJava.setCult(28);
        juego();
        
    }//GEN-LAST:event_cult200ActionPerformed

    private void esp300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp300ActionPerformed
        JuegoJava.setEspa(5);
        JuegoJava.activos[4][0]=!JuegoJava.activos[4][0];
        esp300.setEnabled(JuegoJava.activos[4][0]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_esp300ActionPerformed

    private void mate300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mate300ActionPerformed
        JuegoJava.setMate(11);
        JuegoJava.activos[4][1]=!JuegoJava.activos[4][1];
        mate300.setEnabled(JuegoJava.activos[4][1]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_mate300ActionPerformed

    private void hist300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hist300ActionPerformed
        JuegoJava.setHist(17);
        juego();
        
    }//GEN-LAST:event_hist300ActionPerformed

    private void geo300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geo300ActionPerformed
        JuegoJava.setGeo(23);
        juego();
        
    }//GEN-LAST:event_geo300ActionPerformed

    private void cult300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cult300ActionPerformed
        JuegoJava.setCult(29);
        juego();
        
    }//GEN-LAST:event_cult300ActionPerformed

    private void esp500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp500ActionPerformed
        JuegoJava.setEspa(6);
        JuegoJava.activos[5][0]=!JuegoJava.activos[5][0];
        esp500.setEnabled(JuegoJava.activos[5][0]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_esp500ActionPerformed

    private void mate500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mate500ActionPerformed
        JuegoJava.setMate(12);
        JuegoJava.activos[5][1]=!JuegoJava.activos[5][1];
        mate500.setEnabled(JuegoJava.activos[5][1]);
        this.setVisible(false);
        juego();
        
    }//GEN-LAST:event_mate500ActionPerformed

    private void hist500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hist500ActionPerformed
        JuegoJava.setHist(18);
        juego();
        
    }//GEN-LAST:event_hist500ActionPerformed

    private void geo500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geo500ActionPerformed
        JuegoJava.setGeo(24);
        juego();
        
    }//GEN-LAST:event_geo500ActionPerformed

    private void cult500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cult500ActionPerformed
        JuegoJava.setCult(30);
        juego();
        
    }//GEN-LAST:event_cult500ActionPerformed

    private void geo50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geo50ActionPerformed
        JuegoJava.setGeo(19);
        juego();
        
    }//GEN-LAST:event_geo50ActionPerformed

    private void lbPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbPuntajeActionPerformed
        lbPuntaje.setText(String.valueOf(puntaje));
        
        
    }//GEN-LAST:event_lbPuntajeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton cult100;
    private javax.swing.JButton cult150;
    private javax.swing.JButton cult200;
    private javax.swing.JButton cult300;
    private javax.swing.JButton cult50;
    private javax.swing.JButton cult500;
    private javax.swing.JButton esp100;
    private javax.swing.JButton esp150;
    private javax.swing.JButton esp200;
    private javax.swing.JButton esp300;
    private javax.swing.JButton esp50;
    private javax.swing.JButton esp500;
    private javax.swing.JButton geo100;
    private javax.swing.JButton geo150;
    private javax.swing.JButton geo200;
    private javax.swing.JButton geo300;
    private javax.swing.JButton geo50;
    private javax.swing.JButton geo500;
    private javax.swing.JButton hist100;
    private javax.swing.JButton hist150;
    private javax.swing.JButton hist200;
    private javax.swing.JButton hist300;
    private javax.swing.JButton hist50;
    private javax.swing.JButton hist500;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton56;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lbPuntaje;
    private javax.swing.JButton mate100;
    private javax.swing.JButton mate150;
    private javax.swing.JButton mate200;
    private javax.swing.JButton mate300;
    private javax.swing.JButton mate50;
    private javax.swing.JButton mate500;
    // End of variables declaration//GEN-END:variables
}
